### PR TITLE
Updated ImageButtons as per https://trello.com/c/Z1HCp48w/62-go-throu…

### PR DESCRIPTION
**Pull request by stuxo**
…gh-all-imagebuttons-and-fix-the-background-src-attributes

### CODE REVIEW

**Comment by Twinklebear** [comment]
Looks good! You may want to change your author information and amend the commit, it looks like it didn't tie with your Github account. Also if you're on Trello I can add you as a member to the board.

**Comment by stuxo** [comment]
Hi Will, 

I updated that pull request. That repo should be recognising my github account now.

I can be found on trello with this email or user stuartsimmons.

If theres anything high priority you would like me to look at let me know. I’d really like to help tackle the UI side of things as much as possible.

Cheers,

Stu



On 17 August 2015 at 3:06:33 am, Will Usher (notifications@github.com) wrote:

Looks good! You may want to change your author information and amend the commit, it looks like it didn't tie with your Github account. Also if you're on Trello I can add you as a member to the board.

**Comment by Twinklebear** [comment]
UI stuff would be great, I've been wanting to do some material design stuff on the app for a bit but haven't had the time. If that's something you're interested in working on it'd be great!

**Comment by Twinklebear** [comment]
You should be added to the Trello board now as well.

**Comment by stuxo** [comment]
Yep, great I can edit the trello board now.

I’ll start having a look at putting together a single activity that follows the material design principles for everyone to give feedback on.

I’ll keep you updated.



On 17 August 2015 at 10:24:07 am, Will Usher (notifications@github.com) wrote:

You should be added to the Trello board now as well.

**Comment by stuxo** [comment]
Hi Will,

I created another pull request, tell me what you think when you get a chance.

I’ve had one minor problem with WhatAPI. I’ve noticed that the release jar available doesn’t have the Torrent Group.GetTags() method which is being used in the DescriptionFragment of the app. Is there a jar with these changes included or do I need to build my own jar from the develop branch of WhatAPI?

Stu


On 17 August 2015 at 10:26:50 am, Stuart Simmons (stuart.simmons0@gmail.com) wrote:

Yep, great I can edit the trello board now.

I’ll start having a look at putting together a single activity that follows the material design principles for everyone to give feedback on.

I’ll keep you updated.



On 17 August 2015 at 10:24:07 am, Will Usher (notifications@github.com) wrote:

You should be added to the Trello board now as well.

**Pull request closed without merging**
