### PR TITLE
Material design

### PR DESCRIPTION
**Pull request by stuxo**

### CODE REVIEW

**Comment by Twinklebear** [comment]
For future PR's (and this one I guess) feel free to tag it as [WIP] and I won't merge it in until you feel it's ready to be merged since you can keep pushing to the branch and the new commits will be added to the PR.

**Comment by Twinklebear** [comment]
I finally got some time to check this out, and it looks really good! The profile view looks awesome, the shadows under the headers look great (this should be added in other areas with this layout like requests).

Some things I'm curious about:

- Can we set the color of the notifications bar similar to other material apps and still be compatible? 
- When clicking a recent torrent on a user's profile can we do a button press animation on the album art? I'm not sure how tricky this might be though.

**Comment by stuxo** [comment]
@Twinklebear Can we set the color of the notifications bar similar to other material apps and still be compatible?
Are you referring to the Status Bar? Which has the time etc? 
screen shot 2015-08-31 at 12 11 32 pm

That is currently set to be black, so we can have it whatever colour we want. Right now it is the standard, material dark accent colour.

As for the button press, I'll have a look. We could even look at doing something swanky like this to transition to the torrent group. However, we will likely need to use recycler views which will be a bit of work.

**Comment by Twinklebear** [comment]
Yep the status bar, maybe it didn't show up on the emulator or I missed it but yea, some complementary color for that.

That transition looks extremely fancy! RecylerView is the replacement for ListView right? From a quick search it looks like it, I've been meaning to migrate to the list view replacement for a while. A migration would probably be a decent amount of work since we use lists a lot, let me know if you're interested in working on this, although I can take a look as well.

**Comment by Twinklebear** [comment]
This looks really good! I noticed one smaller thing: It looks like the loading spinner is no longer shown when loading a torrent group page. How will the compatibility be with older Android versions? I'm planning to run in the emulator on some older versions but the emulator is kind of painful to use, if you've done some testing already I'd be interested in hearing how it went :P

**Pull request merged**
