### PR TITLE
Updated profile

### PR DESCRIPTION
**Pull request by stuxo**
This is complete now @Twinklebear

### CODE REVIEW

**Comment by Twinklebear** [comment]
This looks pretty good! I'd like to try it out some but likely won't have time for another week or two since I have some deadlines coming up. For now though, what is the TODO about ranks/snatches not toggling?

**Comment by stuxo** [comment]
@Twinklebear That issue was resolved in commit 3e8409d. Do you want me to build you an APK so you can check out the changes more easily?

**Comment by Twinklebear** [comment]
Ah ok, cool. That's alright, I will have some free time so I'll check it out soon and look at the code some more as well.

**Comment by Twinklebear** [comment]
Hey @stuxo this looks very good! Could you open the PR to the develop branch though and if the new light/dark theme stuff is ready add that and I'll take a look at that as well.

**Pull request closed without merging**
