### PR TITLE
Drawable crash fix

### PR DESCRIPTION
**Pull request by stuxo**
Please review commit fec29b9 to see if this would fix the other issue, with the theme having to be explicitly set.

### CODE REVIEW

**Comment by stuxo** [comment]
I have tested this on android 4.4.2 (galaxy s4) and it works fine. Lets try get this to the people asap.

**Comment by Twinklebear** [comment]
Awesome, could we also remove the hack in https://github.com/Gwindow/WhatAndroid/commit/65dd2e6f6776f45f00cf9e212b5bf45e8221b622 ? It looks like we set a default theme in WhatApplication now, so would things work as expected with themes being set?

**Comment by stuxo** [comment]
Yes, this should be able to be removed. Shall we quote a few people in the thread and ask them to verify this issue has been fixed before pushing the release out?

**Comment by Twinklebear** [comment]
Yea let's remove that hack then ping them about testing the debug build. It'd probably be best to see that the issues are actually fixed before we push out another release :P

**Comment by stuxo** [comment]
Reverted, should be ready to build now.

**Comment by Twinklebear** [comment]
Cool, I'll merge this in develop then ping folks on the forums

**Pull request merged**
